#Allowed block registry ids or tag strings starting with '#'
blocks = [
    "#forge:gems",
    "#forge:logs",
    "#forge:ores",
    "#forge:planks",
    "#forge:raw_materials",
    "#forge:storage_blocks/gems",
    "#forge:storage_blocks/raw_materials",
    "#forge:wood",
    "#minecraft:logs",
    "#minecraft:planks",
    "#minecraft:wood",
    "additional_enchanted_miner:machine_core",
    "additional_enchanted_miner:ore_auto_miner_core",
    "ars_elemental:crystal_air",
    "ars_elemental:crystal_earth",
    "ars_elemental:crystal_fire",
    "ars_elemental:crystal_water",
    "ars_nouveau:arcane_brick",
    "ars_nouveau:mana_gem_block",
    "byg:emeraldite_block",
    "byg:emeraldite_ore",
    "byg:pendorite_block",
    "byg:pendorite_ore",
    "chisel:limestone_raw",
    "chisel:marble_raw",
    "dungeonsarise:crystal_block",
    "dungeonsarise:crystal_ore",
    "enderio:copper_ore",
    "enderio:dark_steel_block",
    "enderio:energetic_alloy_block",
    "enderio:lead_ore",
    "enderio:silver_ore",
    "enderio:tin_ore",
    "enderio:vibrant_alloy_block",
    "forbidden_arcanus:arcane_crystal_block",
    "forbidden_arcanus:arcane_crystal_ore",
    "forbidden_arcanus:darkstone",
    "forbidden_arcanus:deepslate_arcane_crystal_ore",
    "forbidden_arcanus:stella_arcanum_block",
    "forbidden_arcanus:stella_arcanum_ore",
    "forbidden_arcanus:xpetrified_ore",
    "formations:amethyst_block",
    "formations:amethyst_ore",
    "formations:citrine_block",
    "formations:citrine_ore",
    "formations:malachite_block",
    "formations:malachite_ore",
    "formationsnether:quartz_cluster",
    "formationsoverworld:amethyst_cluster",
    "minecraft:acacia_log",
    "minecraft:ancient_debris",
    "minecraft:bamboo_block",
    "minecraft:birch_log",
    "minecraft:cherry_log",
    "minecraft:clay",
    "minecraft:coal_ore",
    "minecraft:copper_ore",
    "minecraft:dark_oak_log",
    "minecraft:deepslate",
    "minecraft:deepslate_coal_ore",
    "minecraft:deepslate_copper_ore",
    "minecraft:deepslate_diamond_ore",
    "minecraft:deepslate_emerald_ore",
    "minecraft:deepslate_gold_ore",
    "minecraft:deepslate_iron_ore",
    "minecraft:deepslate_lapis_ore",
    "minecraft:deepslate_redstone_ore",
    "minecraft:diamond_ore",
    "minecraft:emerald_ore",
    "minecraft:gilded_blackstone",
    "minecraft:gold_ore",
    "minecraft:iron_ore",
    "minecraft:jungle_log",
    "minecraft:lapis_ore",
    "minecraft:mangrove_log",
    "minecraft:nether_gold_ore",
    "minecraft:nether_quartz_ore",
    "minecraft:oak_log",
    "minecraft:redstone_ore",
    "minecraft:sand",
    "minecraft:spruce_log",
    "minecraft:stone",
    "minecraft:stripped_acacia_log",
    "minecraft:stripped_birch_log",
    "minecraft:stripped_cherry_log",
    "minecraft:stripped_dark_oak_log",
    "minecraft:stripped_jungle_log",
    "minecraft:stripped_mangrove_log",
    "minecraft:stripped_oak_log",
    "minecraft:stripped_spruce_log",
    "powah:crystal_blazing",
    "powah:crystal_niotic",
    "powah:crystal_nitro",
    "powah:crystal_spirited",
    "powah:deepslate_uraninite_ore",
    "powah:energized_steel_block",
    "powah:uraninite_ore",
    "regions_unexplored:amber_block",
    "regions_unexplored:amber_ore",
    "regions_unexplored:ruby_block",
    "regions_unexplored:ruby_ore",
    "silentgear:gem_block_azure_electrum",
    "silentgear:gem_block_crimson_steel",
    "silentgear:metal_block_azure_silver",
    "silentgear:metal_block_crimson_iron",
    "silentgear:ore_azure_silver",
    "silentgear:ore_crimson_iron",
    "silentgear:raw_azure_silver_block",
    "silentgear:raw_crimson_iron_block",
    "silentgems:amethyst_block",
    "silentgems:amethyst_ore",
    "silentgems:deepslate_alexandrite_ore",
    "silentgems:deepslate_ammolite_ore",
    "silentgems:deepslate_aquamarine_ore",
    "silentgems:deepslate_black_diamond_ore",
    "silentgems:deepslate_carnelian_ore",
    "silentgems:deepslate_chaos_ore",
    "silentgems:deepslate_citrine_ore",
    "silentgems:deepslate_heliodor_ore",
    "silentgems:deepslate_iolite_ore",
    "silentgems:deepslate_peridot_ore",
    "silentgems:deepslate_ruby_ore",
    "silentgems:deepslate_sapphire_ore",
    "silentgems:garnet_block",
    "silentgems:garnet_ore",
    "silentgems:onyx_block",
    "silentgems:onyx_ore",
    "silentgems:peridot_ore",
    "silentgems:ruby_block",
    "silentgems:ruby_ore",
    "silentgems:sapphire_block",
    "silentgems:sapphire_ore",
    "silentgems:topaz_block",
    "silentgems:topaz_ore"
]

